base: 'https://solr-ddev-site.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ''
    flag: us
    solr_core_read: core_en
  -
    title: Dansk
    enabled: true
    languageId: 1
    base: /da/
    typo3Language: da
    locale: da_DK.UTF-8
    iso-639-1: da
    navigationTitle: Dansk
    hreflang: da-DK
    direction: ''
    fallbackType: fallback
    fallbacks: ''
    flag: dk
    solr_core_read: core_da
    websiteTitle: 'EXT:solr udviklingspakke'
  -
    title: German
    enabled: true
    languageId: 2
    base: /de/
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    fallbackType: fallback
    fallbacks: '1,0'
    flag: de
    solr_core_read: core_de
    websiteTitle: 'EXT:solr Entwicklungspaket'
rootPageId: 1
solr_enabled_read: true
solr_host_read: solr-site
solr_path_read: /
solr_port_read: '8983'
solr_scheme_read: http
solr_use_write_connection: false
websiteTitle: 'EXT:solr development package'

dependencies:
  - dkd/apache-solr-for-typo3-sitepackage
